version: '3'

services:
  web:
    restart: always
    build: ./app
    expose:
      - "8000"
    volumes:
      - app-data:/usr/src/app/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - app-data:/usr/src/app/static
    links:
      - web:web
volumes:
  app-data: