---
- name: Fetch the repo from GitHub
  git:
    repo: 'https://github.com/hmcorreia/localchuck.git'            
    clone: yes
    dest: ./flask-app
    force: yes

- name: Docker Build
  shell: docker build --tag chuck-docker .
  args:
    chdir: ./flask-app/app


- name: Docker Run
  shell: docker run -p 8000:5000 chuck-docker
  args:
    chdir: ./flask-app/app
